import { Injectable, Logger } from '@nestjs/common';
import { ParsedSchema, ParsedEntity } from '../parser/dto/parse-prompt.dto';
import { generatePrismaSchema } from './templates/prisma.template';
import { generateCrudFiles, GeneratedCrudFiles } from './templates/crud.template';
import { generatePackageJson } from './templates/package-json.template';
import { generateAppModule, generateEntityModule } from './templates/module.template';
import {
  generateAuthModule,
  generateAuthService,
  generateAuthController,
  generateJwtStrategy,
  generateJwtAuthGuard,
} from './templates/auth.template';
import {
  generateDockerfile,
  generateDockerCompose,
  generateDockerEnv,
} from './templates/docker.template';
import { generateFrontendFiles } from './templates/frontend.template';
import {
  generateIyzicoService,
  generateIyzicoModule,
  generateIyzicoController,
  generateEFaturaService,
  generateEFaturaModule,
  generateEFaturaController,
  generateKVKKMiddleware,
  generateKVKKDoc,
  generateKVKKPrivacyText,
} from './templates/turkish.template';

export interface GenerateOptions {
  includeTests?: boolean;
  includeDocker?: boolean;
  includeCI?: boolean;
  includeFrontend?: boolean;
  includeIyzico?: boolean;
  includeEFatura?: boolean;
  includeKVKK?: boolean;
}

export interface GeneratedFile {
  path: string;
  content: string;
}

export interface GeneratedProject {
  appName: string;
  prismaSchema: string;
  crudFiles: GeneratedCrudFiles[];
  features: string[];
  summary: {
    entityCount: number;
    fileCount: number;
    features: string[];
  };
  generatedAt: string;
}

function toPascalCase(str: string): string {
  return str.charAt(0).toUpperCase() + str.slice(1);
}

function toKebabCase(str: string): string {
  return str.replace(/([a-z])([A-Z])/g, '$1-$2').toLowerCase();
}

function generateMainTs(): string {
  return `import { NestFactory } from '@nestjs/core';
import { ValidationPipe, Logger } from '@nestjs/common';
import { AppModule } from './app.module';

async function bootstrap() {
  const app = await NestFactory.create(AppModule);
  const logger = new Logger('Bootstrap');

  // Global validation pipe — strips unknown props and transforms types
  app.useGlobalPipes(
    new ValidationPipe({
      whitelist: true,
      forbidNonWhitelisted: true,
      transform: true,
    }),
  );

  // CORS — tighten origins in production
  app.enableCors({
    origin: process.env.ALLOWED_ORIGINS?.split(',') ?? '*',
    credentials: true,
  });

  const port = process.env.PORT ?? 3000;
  await app.listen(port);
  logger.log(\`Application running on http://localhost:\${port}\`);
}

bootstrap();
`;
}

function generateReadme(appName: string, hasAuth: boolean, entities: ParsedEntity[]): string {
  const entityList = entities.map((e) => `- \`${e.name}\``).join('\n');

  return `# ${appName}

> Generated by [PromptForge](https://promptforge.dev)

## Overview

A production-ready NestJS REST API with PostgreSQL (via Prisma ORM).

**Entities**
${entityList}

**Features**
${hasAuth ? '- JWT Authentication (register / login / profile)\n' : ''}- Full CRUD for every entity
- Pagination on list endpoints
- Request validation with class-validator
- Docker + Docker Compose

---

## Prerequisites

- Node.js 20+
- PostgreSQL 16+ (or use Docker Compose)
- npm

---

## Quick start (local)

\`\`\`bash
# 1. Install dependencies
npm install

# 2. Copy environment file and fill in your values
cp .env.example .env

# 3. Apply database migrations
npx prisma migrate dev --name init

# 4. Start the development server
npm run start:dev
\`\`\`

The API will be available at **http://localhost:3000**.

---

## Quick start (Docker)

\`\`\`bash
# Copy and edit environment vars
cp .env.example .env

# Build and start everything
docker compose up -d --build

# The app waits for Postgres to be healthy then runs migrations automatically
\`\`\`

---

## API Reference

${hasAuth ? `### Auth

| Method | Path | Description |
|--------|------|-------------|
| POST | /auth/register | Create account |
| POST | /auth/login | Obtain JWT |
| GET  | /auth/me | Current user (requires JWT) |

> All entity endpoints below require \`Authorization: Bearer <token>\` header.

` : ''}${entities
    .map((e) => {
      const pascal = toPascalCase(e.name);
      const kebab = toKebabCase(pascal);
      const route = kebab + 's';
      return `### ${pascal}

| Method | Path | Description |
|--------|------|-------------|
| POST | /${route} | Create ${e.name} |
| GET | /${route}?page=1&limit=20 | List (paginated) |
| GET | /${route}/:id | Get by ID |
| PATCH | /${route}/:id | Update |
| DELETE | /${route}/:id | Delete |
`;
    })
    .join('\n')}

---

## Environment variables

| Variable | Default | Description |
|----------|---------|-------------|
| DATABASE_URL | — | Prisma connection string |
| JWT_SECRET | — | Secret for signing tokens |
| JWT_EXPIRES_IN | 7d | Token lifetime |
| PORT | 3000 | HTTP port |

---

## Project structure

\`\`\`
src/
├── main.ts            # Entry point
├── app.module.ts      # Root module
${hasAuth ? '├── auth/              # JWT auth module\n' : ''}${entities
    .map((e) => `├── ${toKebabCase(toPascalCase(e.name))}/   # ${e.name} CRUD`)
    .join('\n')}
prisma/
└── schema.prisma      # Database schema
\`\`\`

---

*This project was scaffolded by PromptForge. Happy coding!*
`;
}

@Injectable()
export class GeneratorService {
  private readonly logger = new Logger(GeneratorService.name);

  // ─── Original methods (kept for backward-compat) ─────────────────────────

  generateProject(schema: ParsedSchema): GeneratedProject {
    this.logger.log(
      `Generating project for: ${schema.app_name} (${schema.entities.length} entities)`,
    );

    const prismaSchema = generatePrismaSchema(schema);
    const crudFiles = schema.entities.map((entity) => generateCrudFiles(entity));
    const totalFiles = crudFiles.reduce((acc) => acc + 3, 0);

    const result: GeneratedProject = {
      appName: schema.app_name,
      prismaSchema,
      crudFiles,
      features: schema.features,
      summary: {
        entityCount: schema.entities.length,
        fileCount: totalFiles + 1,
        features: schema.features,
      },
      generatedAt: new Date().toISOString(),
    };

    this.logger.log(
      `Project generated: ${result.summary.fileCount} files for ${result.appName}`,
    );

    return result;
  }

  generateFromSchema(schema: ParsedSchema, options?: GenerateOptions): {
    files: GeneratedFile[];
    summary: GeneratedProject['summary'];
  } {
    const allFiles = this.generateProjectFiles(schema, options);
    const project = this.generateProject(schema);

    return {
      files: allFiles,
      summary: {
        ...project.summary,
        fileCount: allFiles.length,
      },
    };
  }

  // ─── New comprehensive file generation ───────────────────────────────────

  /**
   * Produces every file needed for a complete, runnable NestJS project.
   * The returned array can be zipped and handed directly to the user.
   */
  generateProjectFiles(schema: ParsedSchema, options: GenerateOptions = {}): GeneratedFile[] {
    const hasAuth = schema.features.includes('auth');
    const files: GeneratedFile[] = [];

    // ── package.json ────────────────────────────────────────────────────────
    files.push({
      path: 'package.json',
      content: generatePackageJson(schema.app_name),
    });

    // ── tsconfig.json ───────────────────────────────────────────────────────
    files.push({
      path: 'tsconfig.json',
      content: JSON.stringify(
        {
          compilerOptions: {
            module: 'commonjs',
            declaration: true,
            removeComments: true,
            emitDecoratorMetadata: true,
            experimentalDecorators: true,
            allowSyntheticDefaultImports: true,
            target: 'ES2021',
            sourceMap: true,
            outDir: './dist',
            baseUrl: './',
            incremental: true,
            skipLibCheck: true,
            strictNullChecks: false,
            noImplicitAny: false,
            strictBindCallApply: false,
            forceConsistentCasingInFileNames: false,
            noFallthroughCasesInSwitch: false,
          },
        },
        null,
        2,
      ),
    });

    // ── tsconfig.build.json ─────────────────────────────────────────────────
    files.push({
      path: 'tsconfig.build.json',
      content: JSON.stringify(
        {
          extends: './tsconfig.json',
          exclude: ['node_modules', 'test', 'dist', '**/*spec.ts'],
        },
        null,
        2,
      ),
    });

    // ── nest-cli.json ───────────────────────────────────────────────────────
    files.push({
      path: 'nest-cli.json',
      content: JSON.stringify(
        {
          $schema: 'https://json.schemastore.org/nest-cli',
          collection: '@nestjs/schematics',
          sourceRoot: 'src',
          compilerOptions: { deleteOutDir: true },
        },
        null,
        2,
      ),
    });

    // ── .env.example ────────────────────────────────────────────────────────
    files.push({ path: '.env.example', content: generateDockerEnv() });

    // ── .gitignore ──────────────────────────────────────────────────────────
    files.push({
      path: '.gitignore',
      content: `# Dependencies
node_modules/
dist/

# Environment
.env
.env.local

# Prisma
prisma/*.db
prisma/migrations/

# Logs
*.log
npm-debug.log*

# OS
.DS_Store
Thumbs.db

# IDE
.idea/
.vscode/
*.swp
`,
    });

    // ── Dockerfile & docker-compose.yml ─────────────────────────────────────
    files.push({ path: 'Dockerfile', content: generateDockerfile() });
    files.push({
      path: 'docker-compose.yml',
      content: generateDockerCompose(schema.app_name),
    });

    // ── prisma/schema.prisma ─────────────────────────────────────────────────
    files.push({
      path: 'prisma/schema.prisma',
      content: generatePrismaSchema(schema),
    });

    // ── src/main.ts ──────────────────────────────────────────────────────────
    files.push({ path: 'src/main.ts', content: generateMainTs() });

    // ── src/app.module.ts ────────────────────────────────────────────────────
    files.push({
      path: 'src/app.module.ts',
      content: generateAppModule(schema.entities, hasAuth),
    });

    // ── Entity CRUD files ─────────────────────────────────────────────────────
    for (const entity of schema.entities) {
      const pascal = toPascalCase(entity.name);
      const kebab = toKebabCase(pascal);
      const crud = generateCrudFiles(entity);

      files.push({
        path: `src/${kebab}/dto/create-${kebab}.dto.ts`,
        content: crud.dtoFile.content,
      });
      files.push({
        path: `src/${kebab}/${kebab}.service.ts`,
        content: crud.serviceFile.content,
      });
      files.push({
        path: `src/${kebab}/${kebab}.controller.ts`,
        content: crud.controllerFile.content,
      });
      files.push({
        path: `src/${kebab}/${kebab}.module.ts`,
        content: generateEntityModule(entity.name),
      });
    }

    // ── Auth files (optional) ────────────────────────────────────────────────
    if (hasAuth) {
      files.push({ path: 'src/auth/auth.module.ts', content: generateAuthModule() });
      files.push({ path: 'src/auth/auth.service.ts', content: generateAuthService() });
      files.push({ path: 'src/auth/auth.controller.ts', content: generateAuthController() });
      files.push({
        path: 'src/auth/strategies/jwt.strategy.ts',
        content: generateJwtStrategy(),
      });
      files.push({
        path: 'src/auth/guards/jwt-auth.guard.ts',
        content: generateJwtAuthGuard(),
      });
    }

    // ── iyzico Payment (Turkish) ──────────────────────────────────────────────
    if (options.includeIyzico) {
      files.push({ path: 'src/payment/iyzico.service.ts', content: generateIyzicoService() });
      files.push({ path: 'src/payment/iyzico.module.ts', content: generateIyzicoModule() });
      files.push({ path: 'src/payment/iyzico.controller.ts', content: generateIyzicoController() });
      this.logger.log('iyzico payment files added');
    }

    // ── e-Fatura / e-Arşiv (Turkish GİB) ─────────────────────────────────────
    if (options.includeEFatura) {
      files.push({ path: 'src/einvoice/efatura.service.ts', content: generateEFaturaService() });
      files.push({ path: 'src/einvoice/efatura.module.ts', content: generateEFaturaModule() });
      files.push({ path: 'src/einvoice/efatura.controller.ts', content: generateEFaturaController() });
      this.logger.log('e-Fatura files added');
    }

    // ── KVKK Compliance (Turkish GDPR) ────────────────────────────────────────
    if (options.includeKVKK) {
      files.push({ path: 'src/common/middleware/kvkk.middleware.ts', content: generateKVKKMiddleware() });
      files.push({ path: 'docs/KVKK.md', content: generateKVKKDoc() });
      files.push({ path: 'docs/kvkk-aydinlatma-metni.md', content: generateKVKKPrivacyText() });
      this.logger.log('KVKK compliance files added');
    }

    // ── Next.js Frontend ─────────────────────────────────────────────────────
    if (options.includeFrontend) {
      const frontendFiles = generateFrontendFiles(
        schema.app_name,
        schema.entities,
        hasAuth,
      );
      files.push(...frontendFiles);
      this.logger.log(`Next.js frontend: ${frontendFiles.length} files added`);
    }

    // ── README.md ────────────────────────────────────────────────────────────
    files.push({
      path: 'README.md',
      content: generateReadme(schema.app_name, hasAuth, schema.entities),
    });

    this.logger.log(
      `generateProjectFiles: produced ${files.length} files for "${schema.app_name}"`,
    );

    return files;
  }
}
