/**
 * Express.js + TypeScript project generator.
 * Generates a production-ready REST API with Prisma, JWT auth, and validation.
 */

import { ParsedSchema, ParsedEntity } from '../../parser/dto/parse-prompt.dto';
import { generatePrismaSchema } from './prisma.template';

function toPascalCase(s: string) {
  return s.charAt(0).toUpperCase() + s.slice(1);
}
function toCamelCase(s: string) {
  return s.charAt(0).toLowerCase() + s.slice(1);
}
function toKebabCase(s: string) {
  return s.replace(/([a-z])([A-Z])/g, '$1-$2').toLowerCase();
}

export interface ExpressFile {
  path: string;
  content: string;
}

export function generateExpressProject(schema: ParsedSchema): ExpressFile[] {
  const files: ExpressFile[] = [];
  const hasAuth = schema.features.includes('auth');
  const appName = schema.app_name;
  const kebapApp = toKebabCase(appName).toLowerCase();

  // ── package.json ────────────────────────────────────────────────────────────
  files.push({
    path: 'package.json',
    content: JSON.stringify(
      {
        name: kebapApp,
        version: '0.1.0',
        description: `${appName} — generated by PromptForge`,
        private: true,
        scripts: {
          dev: 'ts-node-dev --respawn --transpile-only src/server.ts',
          build: 'tsc',
          start: 'node dist/server.js',
          lint: 'eslint "src/**/*.ts" --fix',
          test: 'jest',
          'prisma:generate': 'prisma generate',
          'prisma:migrate': 'prisma migrate dev',
          'prisma:migrate:prod': 'prisma migrate deploy',
        },
        dependencies: {
          express: '^4.19.0',
          '@prisma/client': '^5.10.0',
          bcryptjs: '^2.4.3',
          cors: '^2.8.5',
          dotenv: '^16.4.0',
          helmet: '^7.1.0',
          jsonwebtoken: '^9.0.2',
          'express-rate-limit': '^7.2.0',
          zod: '^3.22.0',
          morgan: '^1.10.0',
          'express-validator': '^7.0.1',
        },
        devDependencies: {
          typescript: '^5.3.0',
          '@types/express': '^4.17.21',
          '@types/node': '^20.11.0',
          '@types/bcryptjs': '^2.4.6',
          '@types/cors': '^2.8.17',
          '@types/jsonwebtoken': '^9.0.6',
          '@types/morgan': '^1.9.9',
          '@types/jest': '^29.5.12',
          'ts-node-dev': '^2.0.0',
          'ts-jest': '^29.1.2',
          jest: '^29.7.0',
          prisma: '^5.10.0',
          '@typescript-eslint/eslint-plugin': '^6.21.0',
          '@typescript-eslint/parser': '^6.21.0',
          eslint: '^8.57.0',
        },
      },
      null,
      2,
    ),
  });

  // ── tsconfig.json ────────────────────────────────────────────────────────────
  files.push({
    path: 'tsconfig.json',
    content: JSON.stringify(
      {
        compilerOptions: {
          target: 'ES2021',
          module: 'commonjs',
          lib: ['ES2021'],
          outDir: './dist',
          rootDir: './src',
          strict: false,
          esModuleInterop: true,
          skipLibCheck: true,
          forceConsistentCasingInFileNames: true,
          resolveJsonModule: true,
          declaration: true,
          sourceMap: true,
        },
        exclude: ['node_modules', 'dist', '**/*.spec.ts'],
      },
      null,
      2,
    ),
  });

  // ── .env.example ─────────────────────────────────────────────────────────────
  files.push({
    path: '.env.example',
    content: `DATABASE_URL="postgresql://user:password@localhost:5432/${kebapApp}_db"
JWT_SECRET=change-this-to-a-long-random-secret
JWT_EXPIRES_IN=7d
PORT=3000
ALLOWED_ORIGINS=http://localhost:3001
NODE_ENV=development
`,
  });

  // ── .gitignore ───────────────────────────────────────────────────────────────
  files.push({
    path: '.gitignore',
    content: `node_modules/\ndist/\n.env\n.env.local\nprisma/migrations/\n*.log\n.DS_Store\n`,
  });

  // ── prisma/schema.prisma ──────────────────────────────────────────────────────
  files.push({
    path: 'prisma/schema.prisma',
    content: generatePrismaSchema(schema),
  });

  // ── src/server.ts ─────────────────────────────────────────────────────────────
  files.push({
    path: 'src/server.ts',
    content: `import 'dotenv/config';
import app from './app';

const PORT = parseInt(process.env.PORT ?? '3000', 10);

app.listen(PORT, () => {
  console.log(\`[${appName}] Server running on http://localhost:\${PORT}\`);
  ${hasAuth ? `console.log(\`[${appName}] Health: GET /health\`);` : ''}
});
`,
  });

  // ── src/app.ts ────────────────────────────────────────────────────────────────
  const entityImports = schema.entities
    .map(
      (e) =>
        `import ${toCamelCase(e.name)}Router from './routes/${toKebabCase(toPascalCase(e.name))}.routes';`,
    )
    .join('\n');

  const entityUses = schema.entities
    .map((e) => `app.use('/${toKebabCase(toPascalCase(e.name))}s', ${toCamelCase(e.name)}Router);`)
    .join('\n');

  files.push({
    path: 'src/app.ts',
    content: `import express from 'express';
import cors from 'cors';
import helmet from 'helmet';
import morgan from 'morgan';
import rateLimit from 'express-rate-limit';
${hasAuth ? "import authRouter from './routes/auth.routes';" : ''}
${entityImports}

const app = express();

// ── Security middleware ──────────────────────────────────────────────────────
app.use(helmet());
app.use(cors({
  origin: process.env.ALLOWED_ORIGINS?.split(',') ?? '*',
  credentials: true,
}));

// ── Rate limiting ────────────────────────────────────────────────────────────
app.use(rateLimit({ windowMs: 60_000, max: 100, standardHeaders: true }));

// ── Request parsing ──────────────────────────────────────────────────────────
app.use(express.json({ limit: '10mb' }));
app.use(express.urlencoded({ extended: true }));
app.use(morgan('combined'));

// ── Health check ─────────────────────────────────────────────────────────────
app.get('/health', (_req, res) => res.json({ status: 'ok', app: '${appName}' }));

// ── Routes ────────────────────────────────────────────────────────────────────
${hasAuth ? "app.use('/auth', authRouter);" : ''}
${entityUses}

// ── 404 handler ──────────────────────────────────────────────────────────────
app.use((_req, res) => res.status(404).json({ message: 'Route not found' }));

// ── Error handler ─────────────────────────────────────────────────────────────
app.use((err: any, _req: express.Request, res: express.Response, _next: express.NextFunction) => {
  console.error(err);
  res.status(err.status ?? 500).json({ message: err.message ?? 'Internal server error' });
});

export default app;
`,
  });

  // ── src/lib/prisma.ts ─────────────────────────────────────────────────────────
  files.push({
    path: 'src/lib/prisma.ts',
    content: `import { PrismaClient } from '@prisma/client';

const globalForPrisma = globalThis as unknown as { prisma: PrismaClient };

export const prisma =
  globalForPrisma.prisma ??
  new PrismaClient({
    log: process.env.NODE_ENV === 'development' ? ['query', 'error', 'warn'] : ['error'],
  });

if (process.env.NODE_ENV !== 'production') globalForPrisma.prisma = prisma;

export default prisma;
`,
  });

  // ── src/middleware/auth.middleware.ts (if auth enabled) ──────────────────────
  if (hasAuth) {
    files.push({
      path: 'src/middleware/auth.middleware.ts',
      content: `import { Request, Response, NextFunction } from 'express';
import jwt from 'jsonwebtoken';

export interface AuthRequest extends Request {
  user?: { id: string; email: string };
}

export function authenticate(req: AuthRequest, res: Response, next: NextFunction) {
  const header = req.headers.authorization;
  if (!header?.startsWith('Bearer ')) {
    return res.status(401).json({ message: 'No token provided' });
  }
  const token = header.slice(7);
  try {
    const payload = jwt.verify(token, process.env.JWT_SECRET!) as { sub: string; email: string };
    req.user = { id: payload.sub, email: payload.email };
    next();
  } catch {
    return res.status(401).json({ message: 'Invalid or expired token' });
  }
}
`,
    });

    // ── src/routes/auth.routes.ts ─────────────────────────────────────────────
    const userEntity =
      schema.entities.find((e) => e.name.toLowerCase() === 'user') ??
      schema.entities.find(
        (e) => (schema.auth_entity ?? '').toLowerCase() === e.name.toLowerCase(),
      );

    files.push({
      path: 'src/routes/auth.routes.ts',
      content: `import { Router } from 'express';
import { register, login, me } from '../controllers/auth.controller';
import { authenticate } from '../middleware/auth.middleware';

const router = Router();

router.post('/register', register);
router.post('/login', login);
router.get('/me', authenticate, me);

export default router;
`,
    });

    files.push({
      path: 'src/controllers/auth.controller.ts',
      content: `import { Request, Response } from 'express';
import bcrypt from 'bcryptjs';
import jwt from 'jsonwebtoken';
import prisma from '../lib/prisma';
import { AuthRequest } from '../middleware/auth.middleware';

export async function register(req: Request, res: Response) {
  try {
    const { email, password, name } = req.body;
    if (!email || !password) return res.status(400).json({ message: 'Email and password required' });

    const existing = await prisma.${toCamelCase(userEntity?.name ?? 'user')}.findUnique({ where: { email } });
    if (existing) return res.status(409).json({ message: 'Email already in use' });

    const hashed = await bcrypt.hash(password, 12);
    const user = await prisma.${toCamelCase(userEntity?.name ?? 'user')}.create({
      data: { email, password: hashed, ...(name ? { name } : {}) },
    });

    const token = jwt.sign({ sub: user.id, email: user.email }, process.env.JWT_SECRET!, {
      expiresIn: process.env.JWT_EXPIRES_IN ?? '7d',
    });

    const { password: _, ...userWithoutPassword } = user as any;
    res.status(201).json({ access_token: token, user: userWithoutPassword });
  } catch (err) {
    console.error(err);
    res.status(500).json({ message: 'Registration failed' });
  }
}

export async function login(req: Request, res: Response) {
  try {
    const { email, password } = req.body;
    if (!email || !password) return res.status(400).json({ message: 'Email and password required' });

    const user = await prisma.${toCamelCase(userEntity?.name ?? 'user')}.findUnique({ where: { email } });
    if (!user) return res.status(401).json({ message: 'Invalid credentials' });

    const valid = await bcrypt.compare(password, (user as any).password);
    if (!valid) return res.status(401).json({ message: 'Invalid credentials' });

    const token = jwt.sign({ sub: user.id, email: (user as any).email }, process.env.JWT_SECRET!, {
      expiresIn: process.env.JWT_EXPIRES_IN ?? '7d',
    });

    const { password: _, ...userWithoutPassword } = user as any;
    res.json({ access_token: token, user: userWithoutPassword });
  } catch (err) {
    console.error(err);
    res.status(500).json({ message: 'Login failed' });
  }
}

export async function me(req: AuthRequest, res: Response) {
  try {
    const user = await prisma.${toCamelCase(userEntity?.name ?? 'user')}.findUnique({
      where: { id: req.user!.id },
    });
    if (!user) return res.status(404).json({ message: 'User not found' });
    const { password: _, ...userWithoutPassword } = user as any;
    res.json(userWithoutPassword);
  } catch (err) {
    res.status(500).json({ message: 'Failed to fetch profile' });
  }
}
`,
    });
  }

  // ── Per-entity routes + controllers ──────────────────────────────────────────
  for (const entity of schema.entities) {
    const pascal = toPascalCase(entity.name);
    const camel = toCamelCase(entity.name);
    const kebab = toKebabCase(pascal);
    const route = kebab + 's';

    const userFields = entity.fields.filter(
      (f) => !['id', 'createdAt', 'updatedAt'].includes(f.name),
    );
    const validationLines = userFields
      .filter((f) => f.required)
      .map((f) => `  if (!body.${f.name}) errors.push('${f.name} is required');`)
      .join('\n');

    const dataFields = userFields.map((f) => `      ${f.name}: body.${f.name},`).join('\n');
    const updateFields = userFields
      .map((f) => `      ...(body.${f.name} !== undefined && { ${f.name}: body.${f.name} }),`)
      .join('\n');

    const authImport = hasAuth
      ? `import { authenticate } from '../middleware/auth.middleware';`
      : '';
    const authMiddleware = hasAuth ? 'authenticate, ' : '';

    files.push({
      path: `src/routes/${kebab}.routes.ts`,
      content: `import { Router } from 'express';
${authImport}
import {
  create${pascal},
  findAll${pascal}s,
  findOne${pascal},
  update${pascal},
  remove${pascal},
} from '../controllers/${kebab}.controller';

const router = Router();

router.post('/', ${authMiddleware}create${pascal});
router.get('/', ${authMiddleware}findAll${pascal}s);
router.get('/:id', ${authMiddleware}findOne${pascal});
router.patch('/:id', ${authMiddleware}update${pascal});
router.delete('/:id', ${authMiddleware}remove${pascal});

export default router;
`,
    });

    files.push({
      path: `src/controllers/${kebab}.controller.ts`,
      content: `import { Request, Response } from 'express';
import prisma from '../lib/prisma';

export async function create${pascal}(req: Request, res: Response) {
  try {
    const body = req.body;
    const errors: string[] = [];
${validationLines}
    if (errors.length) return res.status(400).json({ message: errors.join(', ') });

    const item = await prisma.${camel}.create({
      data: {
${dataFields}
      },
    });
    res.status(201).json(item);
  } catch (err: any) {
    if (err.code === 'P2002') return res.status(409).json({ message: 'Unique constraint violation' });
    console.error(err);
    res.status(500).json({ message: 'Failed to create ${camel}' });
  }
}

export async function findAll${pascal}s(req: Request, res: Response) {
  try {
    const page = Math.max(1, parseInt(req.query.page as string) || 1);
    const limit = Math.min(100, parseInt(req.query.limit as string) || 20);
    const skip = (page - 1) * limit;

    const [items, total] = await Promise.all([
      prisma.${camel}.findMany({ skip, take: limit, orderBy: { createdAt: 'desc' } }),
      prisma.${camel}.count(),
    ]);

    res.json({ items, meta: { total, page, limit, totalPages: Math.ceil(total / limit) } });
  } catch (err) {
    console.error(err);
    res.status(500).json({ message: 'Failed to fetch ${camel}s' });
  }
}

export async function findOne${pascal}(req: Request, res: Response) {
  try {
    const item = await prisma.${camel}.findUnique({ where: { id: req.params.id } });
    if (!item) return res.status(404).json({ message: '${pascal} not found' });
    res.json(item);
  } catch (err) {
    res.status(500).json({ message: 'Failed to fetch ${camel}' });
  }
}

export async function update${pascal}(req: Request, res: Response) {
  try {
    const body = req.body;
    const item = await prisma.${camel}.update({
      where: { id: req.params.id },
      data: {
${updateFields}
      },
    });
    res.json(item);
  } catch (err: any) {
    if (err.code === 'P2025') return res.status(404).json({ message: '${pascal} not found' });
    console.error(err);
    res.status(500).json({ message: 'Failed to update ${camel}' });
  }
}

export async function remove${pascal}(req: Request, res: Response) {
  try {
    await prisma.${camel}.delete({ where: { id: req.params.id } });
    res.json({ message: '${pascal} deleted successfully' });
  } catch (err: any) {
    if (err.code === 'P2025') return res.status(404).json({ message: '${pascal} not found' });
    res.status(500).json({ message: 'Failed to delete ${camel}' });
  }
}
`,
    });
  }

  // ── Dockerfile ────────────────────────────────────────────────────────────────
  files.push({
    path: 'Dockerfile',
    content: `FROM node:20-alpine AS builder
WORKDIR /app
COPY package*.json ./
RUN npm ci
COPY . .
RUN npx prisma generate
RUN npm run build

FROM node:20-alpine AS runner
WORKDIR /app
ENV NODE_ENV=production
COPY package*.json ./
RUN npm ci --omit=dev
COPY --from=builder /app/dist ./dist
COPY --from=builder /app/node_modules/.prisma ./node_modules/.prisma
COPY prisma ./prisma
EXPOSE 3000
CMD ["node", "dist/server.js"]
`,
  });

  // ── docker-compose.yml ────────────────────────────────────────────────────────
  files.push({
    path: 'docker-compose.yml',
    content: `services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/${kebapApp}_db
      JWT_SECRET: \${JWT_SECRET:-change-me}
      NODE_ENV: production
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ${kebapApp}_db
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  db_data:
`,
  });

  // ── README.md ─────────────────────────────────────────────────────────────────
  files.push({
    path: 'README.md',
    content: `# ${appName}

> Generated by [PromptForge](https://promptforgeai.dev) — Express.js + TypeScript + Prisma

## Stack

- **Framework:** Express.js 4 + TypeScript
- **ORM:** Prisma (PostgreSQL)
- **Auth:** JWT (jsonwebtoken + bcryptjs)
- **Validation:** Zod + express-validator
- **Security:** Helmet, CORS, rate limiting

## Quick start (local)

\`\`\`bash
npm install
cp .env.example .env
# Edit .env with your DATABASE_URL

npx prisma migrate dev --name init
npm run dev
\`\`\`

Server starts at **http://localhost:3000**.

## Quick start (Docker)

\`\`\`bash
cp .env.example .env
docker compose up -d --build
\`\`\`

## API Reference

### Health

| Method | Path | Description |
|--------|------|-------------|
| GET | /health | Health check |

${
  hasAuth
    ? `### Auth

| Method | Path | Description |
|--------|------|-------------|
| POST | /auth/register | Create account |
| POST | /auth/login | Login, returns JWT |
| GET | /auth/me | Current user (requires Bearer token) |

`
    : ''
}${schema.entities
      .map((e) => {
        const r = toKebabCase(toPascalCase(e.name)) + 's';
        return `### ${toPascalCase(e.name)}

| Method | Path | Description |
|--------|------|-------------|
| POST | /${r} | Create |
| GET | /${r}?page=1&limit=20 | List (paginated) |
| GET | /${r}/:id | Get by ID |
| PATCH | /${r}/:id | Update |
| DELETE | /${r}/:id | Delete |
`;
      })
      .join('\n')}

## Environment variables

| Variable | Description |
|----------|-------------|
| DATABASE_URL | Prisma PostgreSQL connection string |
| JWT_SECRET | JWT signing secret |
| JWT_EXPIRES_IN | Token lifetime (default: 7d) |
| PORT | HTTP port (default: 3000) |

---
*Scaffolded by PromptForge. Happy coding!*
`,
  });

  return files;
}
