import { Injectable, BadRequestException, Logger } from '@nestjs/common';

interface GeneratedFile {
  path: string;
  content: string;
}

export interface ExportResult {
  repoUrl: string;
  owner: string;
  repo: string;
}

@Injectable()
export class GithubService {
  private readonly logger = new Logger(GithubService.name);
  private readonly apiBase = 'https://api.github.com';

  private async ghFetch(
    method: string,
    url: string,
    token: string,
    body?: object,
  ): Promise<any> {
    const res = await fetch(url, {
      method,
      headers: {
        Authorization: `Bearer ${token}`,
        Accept: 'application/vnd.github+json',
        'X-GitHub-Api-Version': '2022-11-28',
        'Content-Type': 'application/json',
      },
      body: body ? JSON.stringify(body) : undefined,
    });
    const data = await res.json();
    if (!res.ok) {
      throw Object.assign(new Error(data?.message ?? res.statusText), { data, status: res.status });
    }
    return data;
  }

  async exportToGithub(
    token: string,
    repoName: string,
    isPrivate: boolean,
    files: GeneratedFile[],
    description?: string,
  ): Promise<ExportResult> {
    // 1. Get authenticated user
    let owner: string;
    try {
      const user = await this.ghFetch('GET', `${this.apiBase}/user`, token);
      owner = user.login;
    } catch {
      throw new BadRequestException('Invalid GitHub token or insufficient permissions.');
    }

    // 2. Create repository
    const safeRepoName = repoName.replace(/[^a-zA-Z0-9._-]/g, '-').toLowerCase();
    try {
      await this.ghFetch('POST', `${this.apiBase}/user/repos`, token, {
        name: safeRepoName,
        description: description ?? 'Generated by PromptForge',
        private: isPrivate,
        auto_init: false,
      });
    } catch (err: any) {
      const msg: string = err?.data?.message ?? err?.message ?? '';
      if (msg.includes('already exists')) {
        throw new BadRequestException(`Repository "${safeRepoName}" already exists in your GitHub account.`);
      }
      throw new BadRequestException(`Failed to create repository: ${msg}`);
    }

    this.logger.log(`Created GitHub repo: ${owner}/${safeRepoName}`);

    // 3. Create all file blobs in parallel
    const blobs = await Promise.all(
      files.map(async (file) => {
        const res = await this.ghFetch(
          'POST',
          `${this.apiBase}/repos/${owner}/${safeRepoName}/git/blobs`,
          token,
          { content: Buffer.from(file.content).toString('base64'), encoding: 'base64' },
        );
        return { path: file.path, sha: res.sha, mode: '100644', type: 'blob' };
      }),
    );

    // 4. Create tree
    const tree = await this.ghFetch(
      'POST',
      `${this.apiBase}/repos/${owner}/${safeRepoName}/git/trees`,
      token,
      { tree: blobs },
    );

    // 5. Create initial commit
    const commit = await this.ghFetch(
      'POST',
      `${this.apiBase}/repos/${owner}/${safeRepoName}/git/commits`,
      token,
      { message: 'Initial commit — generated by PromptForge', tree: tree.sha, parents: [] },
    );

    // 6. Set main branch
    await this.ghFetch(
      'POST',
      `${this.apiBase}/repos/${owner}/${safeRepoName}/git/refs`,
      token,
      { ref: 'refs/heads/main', sha: commit.sha },
    );

    this.logger.log(`Successfully pushed ${files.length} files to ${owner}/${safeRepoName}`);

    return {
      repoUrl: `https://github.com/${owner}/${safeRepoName}`,
      owner,
      repo: safeRepoName,
    };
  }
}
